FROM alpine:3.19.0
ADD "https://github.com/pressly/goose/releases/download/v3.18.0/goose_linux_x86_64" /bin/goose
RUN chmod +x /bin/goose

COPY ./migrations /migrations

ENV GOOSE_DRIVER=mysql
ENV GOOSE_MIGRATION_DIR=/migrations

ENTRYPOINT ["/bin/goose",  "up"]
